# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  sunshine girl
subtitle: 分享技术，品味人生
name: 半只猿的世界你不懂
email: 就是不告诉你！有点皮！
description: 本网站分享博主的工作和生活
keywords: Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico

repository: pandapeggy/myblog.github.io
github_url: https://github.com/pandapeggy
url: http://www.contemplation.top
enforce_ssl: contemplation.top

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  -
    href: /it.html
    label: 技术
    target: _self

  -
    href: /medicalScience.html
    label: 科普
    target: _self

  -
    href: /sports.html
    label: 运动
    target: _self

  -
    href: /photography.html
    label: 摄影
    target: _self

  -
    href: /delicious.html
    label: 下厨房
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  - href: /it.html
    label: 技术
    target: _self
    subnav:

      - subHref: /shell.html
        subLabel: shell

      - subHref: /python.html
        subLabel: python

      - subHref: /other.html
          subLabel: other

  -
    href: /medicalScience.html
    label: 医学科普文
    target: _self

  -
    href: http://www.justdojava.com
    label: 技术类链接
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: Jvm 系列文章

      -
        subHref: http://www.justdojava.com
        subLabel: Java 极客技术
        target: _blank

  -

    href: /sports.html
    label: 运动
    subnav:

      -
        subHref: /run.html
        subLabel: 跑步

      -
        subHref: /keep.html
        subLabel: 其他
        target: _blank

  -
    href: /delicious.html
    label: 下厨房
    target: _self



# labels. my blog key words
labels:

  -
    href: /payment.html
    label: Pay
    target: _self


# selected articles
classes:

  -
    href: /sports.html
    name: 爱运动
    describe: 运动很简单，坚持靠毅力

  -
    href: /delicious.html
    name: 下厨房
    describe: 上得了厅堂，下得了厨房

  -
    href: /it.html
    name: IT行业深度报道
    describe: IT大佬，互联网知名公司的故事




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments评论区域开启    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: pandapeggy
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: pandapeggy
    repo: blog-comments
    oauth:
        client_id: aac6d6aa1b6690b5b9a8
        client_secret: c1a02a1af46128d0240aaef2d89ed135d1897429
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: pandapeggy
    repo: blog-comments
    clientID: aac6d6aa1b6690b5b9a8
    clientSecret: c1a02a1af46128d0240aaef2d89ed135d1897429
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

theme: jekyll-theme-tactile